import os
import raylibpy

MAX_X = 800
MAX_Y = 600
FRAME_RATE = 30

DEFAULT_SQUARE_SIZE = 20
DEFAULT_FONT_SIZE = 20
DEFAULT_TEXT_OFFSET = 4

IMAGE_PLAYER_RED = ""
IMAGE_PLAYER_BLUE = os.path.join(os.getcwd(), "./assets/player.png")

IMAGE_PLATFORM = ""

IMAGE_ENEMY_RED = ""
IMAGE_ENEMY_BLUE = ""

IMAGE_CRYSTAL_RED = ""
IMAGE_CRYSTAL_BLUE = ""

SOUND_START = ""
SOUND_OVER = ""

PLAYER_X = MAX_X / 2
PLAYER_Y = MAX_Y - 125

PLAYER_DX = 8
PLAYER_DY = PLAYER_DX * -1

PLAYER_WIDTH = 100
PLAYER_HEIGHT = 200

PLAYER_SPEED = 10